FROM node:16-bullseye

RUN apt-get update
RUN apt-get install build-essential

WORKDIR /app
COPY ./package.json ./package-lock.json ./yarn.lock ./
RUN yarn install

COPY . /app/

CMD [ "npm", "run", "watch" ]

