# FROM node:10 as node

# WORKDIR /app
# COPY ./package.json ./package-lock.json ./
# RUN npm ci

# COPY . .
# RUN npx webpack --config webpack.development.config.js

FROM python:3.9 as python

ENV DOCKER_CONTAINER=True

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./Pipfile ./Pipfile.lock /app/
WORKDIR /app
RUN pipenv install --dev --system

COPY . /app/
# COPY --from=node /app/pipeline/static/webpack_bundles/ /app/pipeline/static/webpack_bundles/
# COPY --from=node /app/webpack-stats.json /app/

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]