language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
  
before_install:
  - pip install pipenv
  - npm install -g npm@"^6.4.0"

install:
  - pipenv install --dev --deploy
  - npm ci
  - npx webpack --config webpack.development.config.js
    
before_script:
  - pipenv check
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check --exclude node_modules/; fi
  - flake8 --exclude node_modules/ || true

script:
  - pipenv run python manage.py test
