version: '2'
services:
  api:
    build: api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
  redis:
    image: redis:3.2
  rt-editor:
    build: rt-editor
    ports:
      - "8002:8002"
    volumes:
      - ./rt-editor:/app
    links:
      - redis
  web:
    build: web
    ports:
      - "8000:80"
    volumes:
      - ./web:/app
      - /app/node_modules
