version: '2'
services:
  django:
    build:
      context: .
    networks:
      - django-nginx
    volumes:
      - django-static:/app/static
    ports:
      - 8000
    environment:
      - SECRET_KEY
    depends_on:
      - postgres
  nginx:
    build:
      context: ./nginx
    ports:
      - "8001:8000"
    networks:
      - django-nginx
    volumes:
      - django-static:/app/static
    ports:
      - 8000:80
    depends_on:
      - django
  postgres:
    image: postgres:10
    networks:
      - django-nginx
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
      POSTGRES_DB: pipeline
volumes:
  django-static:
  postgres-data:

networks:
  django-nginx:
    driver: bridge
