version: '2'
services:
  api:
    build: api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
  web:
    build: web
    ports:
      - "8000:80"
    volumes:
      - ./web:/app
      - /app/node_modules
