version: '3'
services:
  web:
    build: web
    ports:
      - "3000:80"
    volumes:
      - ./web:/app
      - /app/node_modules
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
