# Generated by Django 2.2.9 on 2020-01-31 02:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0012_auto_20200131_0237")]

    operations = [
        migrations.AddField(
            model_name="electionindexpage",
            name="featured_articles",
            field=wagtail.fields.StreamField(
                [
                    (
                        "one_column_candidate",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "one_column_article",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        )
    ]
