# Generated by Django 2.2.28 on 2022-07-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20220327_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
    ]
