version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - "${HOST_PROJECT_PATH:-.}/dev-docker/db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipeline


  django:
    container_name: django
    build:
      dockerfile: ./dev-docker/Dockerfile
      context: ..
    #command: python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY:
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres-data: