# Generated by Django 2.2.5 on 2019-09-24 23:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("home", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="featured_articles",
            field=wagtail.fields.StreamField(
                [
                    (
                        "one_column",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "one_ad_column",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"], required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.URLBlock(
                                        label="target", required="false"
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "Small"),
                                            ("medium", "Medium"),
                                            ("large", "Large"),
                                        ],
                                        help_text="Width of image in ad.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "two_columns",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "left_column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "right_column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "emphasize_column",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("right", "Right")],
                                        help_text="Which article, if either, should appear larger.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "three_columns",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "left_column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "middle_column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "right_column",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "article",
                                                wagtail.blocks.PageChooserBlock(
                                                    page_type=["core.ArticlePage"]
                                                ),
                                            ),
                                            (
                                                "headline",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Optional. Will override the article's headline.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "recent_articles",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "num_articles",
                                    wagtail.blocks.IntegerBlock(
                                        help_text="Number of recent articles to display.",
                                        label="Number of articles",
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        )
    ]
